// A comprehensive database of car makes and their corresponding models.
// Contains major global and Indian manufacturers to cover a wide spectrum.

const carDatabase = {
    "Acura": ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX", "Integra", "ZDX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C", "8C"],
    "Aston Martin": ["DB11", "DB12", "DBX", "Vantage", "DBS Superleggera", "Valkyrie"],
    "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "e-tron", "RS3", "RS5", "RS6", "RS7", "RS Q8"],
    "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z4", "i3", "i4", "i7", "iX", "M2", "M3", "M4", "M5", "M8"],
    "Bugatti": ["Chiron", "Veyron", "Divo", "Centodieci", "Bolide"],
    "Buick": ["Enclave", "Encore", "Envision"],
    "Cadillac": ["CT4", "CT5", "Escalade", "XT4", "XT5", "XT6", "Lyriq"],
    "Chevrolet": ["Camaro", "Corvette", "Malibu", "Spark", "Equinox", "Traverse", "Tahoe", "Suburban", "Colorado", "Silverado", "Blazer", "Trailblazer", "Trax", "Cruze"],
    "Chrysler": ["300", "Pacifica", "Voyager"],
    "Citroen": ["C3", "C4", "C5 Aircross", "Berlingo"],
    "Dodge": ["Challenger", "Charger", "Durango", "Hornet"],
    "Ferrari": ["812 Superfast", "296 GTB", "F8 Tributo", "SF90 Stradale", "Roma", "Portofino M", "Purosangue", "LaFerrari"],
    "Fiat": ["500", "500X", "Panda", "Tipo", "Pulse"],
    "Ford": ["Mustang", "F-150", "Explorer", "Escape", "Bronco", "Bronco Sport", "Edge", "Expedition", "Ranger", "Maverick", "Focus", "Fiesta", "EcoSport", "Endeavour"],
    "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
    "GMC": ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon", "Hummer EV"],
    "Honda": ["Accord", "Civic", "CR-V", "HR-V", "Pilot", "Odyssey", "Passport", "Ridgeline", "Fit", "City", "Amaze", "Elevate"],
    "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade", "Kona", "Venue", "Ioniq 5", "Ioniq 6", "Creta", "Verna", "i20", "Alcazar", "Aura", "Exter"],
    "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
    "Jaguar": ["E-PACE", "F-PACE", "I-PACE", "F-TYPE", "XE", "XF"],
    "Jeep": ["Cherokee", "Grand Cherokee", "Compass", "Renegade", "Wrangler", "Gladiator", "Wagoneer", "Meridian"],
    "Kia": ["Forte", "K5", "Stinger", "Soul", "Seltos", "Sportage", "Sorento", "Telluride", "Carnival", "EV6", "EV9", "Sonet", "Carens"],
    "Lamborghini": ["Aventador", "Huracan", "Urus", "Revuelto"],
    "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Discovery", "Discovery Sport", "Defender"],
    "Lexus": ["IS", "ES", "LS", "NX", "RX", "GX", "LX", "RC", "LC", "UX"],
    "Lincoln": ["Corsair", "Nautilus", "Aviator", "Navigator"],
    "Lotus": ["Emira", "Evija", "Eletre"],
    "Maserati": ["Ghibli", "Quattroporte", "Levante", "MC20", "Grecale"],
    "Mazda": ["Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-50", "CX-9", "CX-90", "MX-5 Miata"],
    "McLaren": ["720S", "750S", "Artura", "GT", "Senna", "P1"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "EQE", "EQS", "AMG GT"],
    "MG": ["Hector", "Astor", "Gloster", "ZS EV", "Comet EV", "MG4"],
    "Mini": ["Cooper", "Countryman", "Clubman"],
    "Mitsubishi": ["Outlander", "Eclipse Cross", "Mirage", "Pajero"],
    "Nissan": ["Altima", "Maxima", "Sentra", "Versa", "370Z", "Z", "GT-R", "Kicks", "Rogue", "Murano", "Pathfinder", "Armada", "Frontier", "Titan", "Ariya", "Magnite"],
    "Pagani": ["Huayra", "Zonda", "Utopia"],
    "Peugeot": ["208", "308", "2008", "3008", "5008", "508"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718 Boxster", "718 Cayman"],
    "Ram": ["1500", "2500", "3500", "ProMaster"],
    "Renault": ["Clio", "Megane", "Captur", "Duster", "Kwid", "Triber", "Kiger"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre"],
    "Skoda": ["Octavia", "Superb", "Kodiaq", "Karoq", "Kamiq", "Slavia", "Kushaq"],
    "Subaru": ["Impreza", "Legacy", "Crosstrek", "Forester", "Outback", "Ascent", "BRZ", "WRX"],
    "Suzuki / Maruti Suzuki": ["Swift", "Baleno", "Dzire", "Ertiga", "Brezza", "Celerio", "WagonR", "Ignis", "Fronx", "Grand Vitara", "Jimny"],
    "Tata": ["Nexon", "Punch", "Harrier", "Safari", "Tiago", "Tigor", "Altroz"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
    "Toyota": ["Camry", "Corolla", "Avalon", "Prius", "Yaris", "86", "Supra", "C-HR", "RAV4", "Venza", "Highlander", "4Runner", "Sequoia", "Land Cruiser", "Tacoma", "Tundra", "Sienna", "Fortuner", "Innova", "Glanza", "Urban Cruiser"],
    "Volkswagen": ["Jetta", "Passat", "Arteon", "Golf", "GTI", "ID.4", "Taos", "Tiguan", "Atlas", "Touareg", "Polo", "Vento", "Virtus", "Taigun"],
    "Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40 Recharge"]
};
